export default {
  employeeList: 'Employee List',
  employees: 'Employees',
  addNew: 'Add New',
  addEmployee: 'Add Employee',
  editEmployee: 'Edit Employee',
  firstName: 'First Name',
  lastName: 'Last Name',
  dateOfEmployment: 'Date of Employment',
  dateOfBirth: 'Date of Birth',
  phone: 'Phone',
  email: 'Email',
  department: 'Department',
  position: 'Position',
  analytics: 'Analytics',
  tech: 'Tech',
  junior: 'Junior',
  medior: 'Medior',
  senior: 'Senior',
  search: 'Search',
  list: 'List',
  table: 'Table',
  edit: 'Edit',
  delete: 'Delete',
  areYouSure: 'Are you sure?',
  confirmDelete:
    'Selected Employee record of {firstName} {lastName} will be deleted',
  proceed: 'Proceed',
  cancel: 'Cancel',
  save: 'Save',
  required: 'Required',
  invalidEmail: 'Invalid email',
  invalidPhone: 'Invalid phone',
  uniqueError: 'Employee with this email or phone already exists',
  actions: 'Actions',
  noResults: 'No employees found.',
  page: 'Page',
  of: 'of',
  next: 'Next',
  prev: 'Previous',
  youAreEditing: 'You are editing {firstName} {lastName}',
};
