export default {
  employeeList: 'Çalışan Listesi',
  employees: 'Çalışanlar',
  addNew: 'Yeni Ekle',
  addEmployee: 'Çalışan Ekle',
  editEmployee: 'Çalışan Düzenle',
  firstName: 'Adı',
  lastName: 'Soyadı',
  dateOfEmployment: 'İşe Giriş Tarihi',
  dateOfBirth: 'Doğum Tarihi',
  phone: 'Telefon Numarası',
  email: 'E-posta',
  department: 'Departman',
  position: 'Pozisyon',
  analytics: 'Analitik',
  tech: 'Teknoloji',
  junior: 'Junior',
  medior: 'Medior',
  senior: 'Senior',
  search: 'Ara',
  list: 'Liste',
  table: 'Tablo',
  edit: 'Düzenle',
  delete: 'Sil',
  areYouSure: 'Emin misiniz?',
  confirmDelete: '{firstName} {lastName} çalışan kaydı silinecek',
  cancel: 'İptal',
  save: 'Kaydet',
  required: 'Zorunlu',
  invalidEmail: 'Geçersiz e-posta',
  invalidPhone: 'Geçersiz telefon',
  uniqueError: 'Bu e-posta veya telefon ile kayıtlı çalışan var',
  actions: 'İşlemler',
  noResults: 'Çalışan bulunamadı.',
  page: 'Sayfa',
  of: '/',
  next: 'İleri',
  prev: 'Geri',
  youAreEditing: '{firstName} {lastName} düzenliyorsunuz',
};
